#Language used
language: python

#python version used
python:
  - "3.5.2"

#packages to be installed
install:
  - pip install -r requirements.txt
env:
- export PRIV="fast-food-fast"
- export SECRET_KEY="f7fc15525d64cbc8985fe15281c822deb8f19a482650107a"
- export JWT_SECRET_KEY="f7fc789385fe15281c822deb8f19a482650107a"

before_script:
#command to create testdb
- psql -c 'CREATE DATABASE testfastfoodfast;' -U postgres

script: 
  #command to run tests
  - cd tests
  - pytest --cov=v2/

after_success:
  - coveralls

# command to start postgresql
services:
  - postgresql
