#Language used
language: python

#python version used
python:
  - "3.5.2"

#Environment variable for the build
env:
 - export TDB_URL="dbname='testfastfoodfast' host='localhost' user='dario' password='riot'"
 
#packages to be installed
install:
  - pip install -r requirements.txt

before_script:
#command for creating role in database
- psql -c "CREATE ROLE dario WITH SUPERUSER LOGIN PASSWORD 'riot';" -U postgres
#command to create testdb
- psql -c 'CREATE DATABASE testfastfoodfast;' -U postgres

script: 
  #command to run tests
  - cd tests/v2
  - pytest 

# command to start postgresql
services:
  - postgresql
