#Language used
language: python

#python version used
python:
  - "3.5.2"

#packages to be installed
install:
  - pip install -r requirements.txt

before_script:
- export TDB_URL="dbname='testfastfoodfast' host='localhost' user='dario' password='riot'"
- export SECRET="f7fc15525d64cbc8985fe15281c822deb8f19a482650107a"
#command for creating role in database
- psql -c "CREATE ROLE dario WITH SUPERUSER LOGIN PASSWORD 'riot';" -U postgres
#command to create testdb
- psql -c 'CREATE DATABASE testfastfoodfast;' -U postgres

script: 
  #command to run tests
  - cd tests
  - pytest 

after_success:
  - coveralls

# command to start postgresql
services:
  - postgresql
