#Language used
language: python

#python version used
python:
  - "3.5.2"

#packages to be installed
install:
  - pip install -r requirements.txt

#run tests with
script:
  - cd app/a_p_i/v1/tests
  - nosetests  --with-coverage --cover-package=app/a_p_i/v1/views

# command to run test coverage
after_success:
  - coveralls