language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  # - cd API_V1/tests
  # - nosetests  --with-coverage --cover-package=resources
  - py.test --cov=API_V1/tests/

after_success:
  - coveralls